# -*- coding: utf-8 -*-
"""TelcoChurn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KMxdGLm2RcY5vLxbmmUSJM5yqIKpMPjs
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,StandardScaler,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV, KFold

df=pd.DataFrame(pd.read_csv('Telco.csv'))
df.head(3)

df.tail(3)

df.shape

df.columns

df.isnull().sum()
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df.dropna(subset=['TotalCharges'], inplace=True)
numerical_data=df.select_dtypes(include='number')
numerical_data.shape

X=df.drop(columns=['Churn','customerID'])
y=df['Churn']

from sklearn.compose import ColumnTransformer

encoder=LabelEncoder()
y_encoded=encoder.fit_transform(y)
X_train,X_test,y_train,y_test=train_test_split(X,y_encoded,random_state=42,test_size=0.5)
numerical_columns=X_train.select_dtypes(exclude='object').columns
categorical_columns=X_train.select_dtypes(include='object').columns

preprocessing=ColumnTransformer(
    transformers=[
        ('numerical',StandardScaler(),numerical_columns),
        ('categorical',OneHotEncoder(handle_unknown='ignore'),categorical_columns)
    ],
    remainder='passthrough',
)
X_train_scaled=preprocessing.fit_transform(X_train)
X_test_scaled=preprocessing.transform(X_test)

kv=KFold(n_splits=10)
params1={

    'max_depth':[5,6,7],
    'min_samples_split':[5,10,20]
}
params2={
    'C':[300,500,700],
    'max_iter':[10,30,50],
}
cv_lr=GridSearchCV(
    LogisticRegression(),
    cv=kv,
    param_grid=params2,
)
cv_tree=GridSearchCV(
    DecisionTreeClassifier(),
    cv=kv,
    param_grid=params1,
)
cv_forest=GridSearchCV(
    RandomForestClassifier(),
    cv=kv,
    param_grid=params1,
)
cv_xgb=GridSearchCV(
    XGBClassifier(),
    cv=kv,
    param_grid=params1,
)

cv_lr.fit(X_train_scaled,y_train)

cv_tree.fit(X_train_scaled,y_train)

cv_forest.fit(X_train_scaled,y_train)

cv_xgb.fit(X_train_scaled,y_train)

y_pred_regression=cv_lr.predict(X_test_scaled)
y_pred_tree=cv_tree.predict(X_test_scaled)
y_pred_forest=cv_forest.predict(X_test_scaled)
y_pred_xgb=cv_xgb.predict(X_test_scaled)

#METRICS

print("Accuracy score of Logistic Regression:",accuracy_score(y_test,y_pred_regression)*100,"%")
print("Accuracy score in Decision Tree Classifier:",accuracy_score(y_test,y_pred_tree)*100,"%")
print("Accuracy score in Random Forest Classifier:",accuracy_score(y_test,y_pred_forest)*100,"%")
print("Accuracy score of XGB Classifer:",accuracy_score(y_test,y_pred_xgb)*100,"%")

#Logistic Regression model has the highest accuracy so we will use it

print("Logistic Regression:\n",classification_report(y_test,y_pred_regression))
print("Decision Tree Classifier:\n",classification_report(y_test,y_pred_tree))
print("Random Forest Classifier:\n",classification_report(y_test,y_pred_forest))
print("XGB Classifier:\n",classification_report(y_test,y_pred_xgb))

cmap1=confusion_matrix(y_test,y_pred_regression)
sns.heatmap(cmap1,cmap='Blues',annot=True)
plt.show()
cmap2=confusion_matrix(y_test,y_pred_tree)
sns.heatmap(cmap2,cmap='Blues',annot=True)
plt.show()
cmap3=confusion_matrix(y_test,y_pred_forest)
sns.heatmap(cmap3,cmap='Blues',annot=True)
plt.show()
cmap4=confusion_matrix(y_test,y_pred_xgb)
sns.heatmap(cmap4,cmap='Blues',annot=True)
plt.show()


from sklearn.pipeline import Pipeline
model=Pipeline(
    [('preprocessing',preprocessing),
    ('model',cv_lr)]
)
import pickle as pkl
with open("model.pkl","wb") as f:
    pkl.dump(model,f)